### ISSUE TITLE
Future player divs not removed a null div is attempted to be accessed 

### ISSUE THREAD

**Issue by robbiehammond** [CSDS393CDFGHK/Hivemind#24]
Pretty self explanatory. Should be pretty straightforward to fix by making a "permanent" player div that is always invisible. When a new div is needed, just copy that one, and then set the new div to visible. It also might be required to change how the 'nextDivNum' variable functions in client.js to fully ensure a deleted div is never accessed.

**Comment by andrew0144** [comment]
![image](https://user-images.githubusercontent.com/80224229/142244348-7114edf3-879e-4336-8936-c9a115301df9.png)
was this the bug in question?

**Comment by robbiehammond** [comment]
Bug might be fixed on frontend branch now in commit 9a8b40a. Didn't do any rigorous testing, but it's at least harder to trigger.
