### ISSUE TITLE
triggerGameStart msg never gets sent to frontend

### ISSUE THREAD

**Issue by robbiehammond** [CSDS393CDFGHK/Hivemind#27]
It seems like the output message of triggerGameStart is never sent to the frontend, presumably because the result of the triggerGameStart function call in handleReadyChange (only place where triggerGameStart seems to be called) is never assigned to a variable or otherwise used. Because of this, the output of triggerGameStart is lost and never gets sent from the server. A very easy fix to this would be doing something like this:
![Screenshot from 2021-11-20 15-12-41](https://user-images.githubusercontent.com/58093703/142739719-c9b58744-fc78-4072-93ad-710e03e859ac.png)
This edit seems to allow the frontend to receive the message appropriately. However, I'm not sure if the current behavior is intentional and there is another mechanism in which the message will be sent that I have not seen, so I haven't made a pull request or marked this as a bug. If it isn't intentional, I can make a pull request and get this fix on the devel branch.

**Comment by edf42001** [comment]
I agree, the function returns a message but nothing happens to it. You can go ahead and fix it. Also I interpret the `invalid` label for github issues that aren't real issues (incorrect issues). This may be better as question/bug.
