### ISSUE TITLE
Ready status of existing players is not displayed on new player's screen when they join

### ISSUE THREAD

**Issue by edf42001** [CSDS393CDFGHK/Hivemind#29]
Also if you haven't gotten a chance to look at cookies yet, and would like to pawn it off to me, I'd be fine with that

**Comment by robbiehammond** [comment]
I actually fixed this in one of the commits currently in the frontend branch

**Comment by robbiehammond** [comment]
I’d link it but I’m currently on mobile. Check which commit says “(you)s fixed” or something like that

**Comment by robbiehammond** [comment]
This commit: df90119f8a35c538efef2bc0c923524865459e73

And as for the cookies, I sorta forgot about them, but I can work on them and hopefully finish them tomorrow.
